<?php 
/** 
* Declare what blocks are provided by this module. 
* Implements hook_block_info(). 
*/ 

function dynamic_blocks_block_info(){ 
	// This block is for downloading advocacy guides.
	$block['download_guides'] = array(
		'info' => t('Download Advocacy Guides'),
		'cache' => DRUPAL_NO_CACHE, 		
	); 
	
	// This block is for email a friend webform.
	$block['email_friend'] = array(	
		'info' => t('Email to Friend'), //title on blocks page
		'cache' => DRUPAL_NO_CACHE,				
	);

	return $block; 
} 

/** 
* Create an admin settings screen. 
*/ 
function dynamic_blocks_menu(){
  $items = array();
  $items['admin/config/user-interface/dynamic_blocks'] = array(
    'title' => 'Dynamic Box - download advocacy guide settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dynamic_blocks_admin_form'),
    'access arguments' => array('access administration menu'),
  );
  return $items;
}

/** 
* Define what our blocks will look like. 
* Implements hook_block_view(). 
*/ 

function dynamic_blocks_block_view($delta =''){
	$block = array(); 
	
	switch ($delta) {
    case 'download_guides':
			// Individual block code is in its .inc file
			module_load_include('inc', 'dynamic_blocks', 'download_adv_guide');
	
			//Define the block title and content. 
			$block = array(
				'subject' => t('Download Advocacy Guides'), 			
			  'content' => generate_content($list),
			);
			break;
			
    case 'email_friend':
			// Individual block code is in its .inc file
			module_load_include('inc', 'dynamic_blocks', 'email_friend');						
			
			// Display this link in our block
			$block = array(
				'subject' => t('Email'), 		
				'content' => generate_link($items), 
			);
			break;
	}
		return $block;
 }

 /** 
* Use this settings screen to enter hard copy book url at MCLE, they change each year. 
*/ 

 function dynamic_blocks_admin_form($form, &$form_state) {
  $form = array();
  $form['hard_copy_url_ea'] = array(
      '#type' => 'textfield',
	  '#title' => t('EA Advocacy Guide - Hard Copy URL'),
      '#default_value' => variable_get('hard_copy_url_ea', 'enter url-ea'),
      '#description' => t('This URL requires update every year, and is used in the Download Advocacy Guide yellow-box block.'),
	  '#size' => 100,
  );
  $form['hard_copy_url_tafdc'] = array(
      '#type' => 'textfield',
	  '#title' => t('TAFDC Advocacy Guide - Hard Copy URL'),
      '#default_value' => variable_get('hard_copy_url_tafdc', 'enter url-tafdc'),
      '#description' => t('This URL requires update every year, and is used in the Download Advocacy Guide yellow-box block.'),
	  '#size' => 100,
  );
  $form['hard_copy_url_snap'] = array(
      '#type' => 'textfield',
	  '#title' => t('Food Stamps (SNAP) Advocacy Guide - Hard Copy URL'),
      '#default_value' => variable_get('hard_copy_url_snap', 'enter url-snap'),
      '#description' => t('This URL requires update every year, and is used in the Download Advocacy Guide yellow-box block.'),
	  '#size' => 100,
  );
  
  return system_settings_form($form);
}