<?php 
/** 
* Declare what blocks are provided by this module. 
* Implements hook_block_info(). 
*/ 

function dynamic_blocks_block_info(){ 
	// This block is for downloading advocacy guides.
	$block['download_guides'] = array(
		'info' => t('Download Advocacy Guides'),
		'cache' => DRUPAL_NO_CACHE, 		
	); 
	
	// This block is for email a friend webform.
	$block['email_friend'] = array(	
		'info' => t('Email to Friend'), //title on blocks page
		'cache' => DRUPAL_NO_CACHE,				
	);

	return $block; 
} 

/** 
* Define what our blocks will look like. 
* Implements hook_block_view(). 
*/ 

function dynamic_blocks_block_view($delta =''){
	$block = array(); 
	
	switch ($delta) {
    case 'download_guides':
			// Individual block code is in its .inc file
			module_load_include('inc', 'dynamic_blocks', 'download_adv_guide');
	
			//Define the block title and content. 
			$block = array(
				'subject' => t('Download Advocacy Guides'), 			
			  'content' => generate_content($list),
			);
			break;
			
    case 'email_friend':
			// Individual block code is in its .inc file
			module_load_include('inc', 'dynamic_blocks', 'email_friend');						
			
			// Display this link in our block
			$block = array(
				'subject' => t('Email'), 		
				'content' => generate_link($items), 
			);
			break;
  }
		return $block;
 }
