<?php 
/** 
* Declare what blocks are provided by this module. 
* Implements hook_block_info(). 
*/ 

function dynamic_blocks_block_info(){ 
	$block['download_guides'] = array(
		'info' => t('Download Advocacy Guides'),
		'cache' => DRUPAL_NO_CACHE, 
	); 
	
	return $block; 
} 

/** 
* Define what our block is going to look like. 
* Implements hook_block_view(). 
*/ 

function dynamic_blocks_block_view($block_key = ''){
	$block = array(); 

	if($block_key == 'download_guides'){ 	
	
		//Define the block title. 
		$block['subject'] = t('Download Advocacy Guides'); 
		//$block['title_attributes_array'][] = 'class';	
		//$block['title_attributes_array']['class'] = 'yellow-block'; 
		
		//Define the block content. 	
		$block['content'] = generate_content($list);
		
		return $block;
 }
}

function generate_content(&$list) {
		// 1. Get current page url and breadcrumb    	 
		$url = drupal_get_path_alias($_GET['q']);
    $menuTrail = menu_get_active_trail("node/$node->nid"); 	 
	 
	  // 2. Construct pdf file title and download path
	  // 2.a Get text from the breadcrumb and use it as the PDF display title
    $pdfDisplayTitle = array();
	  $pdfDisplayTitle["chapter"]=$menuTrail[6]["title"];	 
	  $pdfDisplayTitle["guide"]=$menuTrail[5]["title"];	 
	  $pdfDisplayTitle["ePub"] = $pdfDisplayTitle["guide"]." for Android or i-devices";
	  $pdfDisplayTitle["mobi"] = $pdfDisplayTitle["guide"]." for Kindle";
	 
	  // 2.b Change blank space to "-" and convert the pdf file name to lower case 
	  $pdfName=array();
	  $pdfName["guide"] = strtolower(str_replace(' ', '-', $pdfDisplayTitle["guide"]));
    $pdfName["chapter"] = strtolower(str_replace(' ', '-', $pdfDisplayTitle["chapter"]));

    // 3. Construct download links
	  // 3.a For question pages, remove the last piece (/partx) from the url
    if (is_numeric(substr($url, -1))) {
      $url=dirname($url);
    }
		
	  $pdfPath = array();
    $pdfPath["chapter"] = $url."/".$pdfName["chapter"].".pdf";
    $pdfPath["ePub"] = dirname(dirname($url))."/".$pdfName["guide"].".epub";
	  $pdfPath["mobi"] = dirname(dirname($url))."/".$pdfName["guide"].".mobi"; 

    // 4. Generate links list
    // 4a. For chapter and its children pages, display the chapter pdf download link
    $list = array();
		if ($pdfName["chapter"] >= "a") {	  
		  $prefix = '<p><img src="/mhl-shared/images/pdf.gif" /> ';		
      $title = $pdfDisplayTitle["chapter"];		
		  $href = $pdfPath["chapter"];
		  $list[] = addtolist($listItem, $title, $href, $prefix);			
	  };		// end of chapter pdf download
		
		// 4b. For chapter pages, display the full guide pdf download link 	
		if (empty($menuTrail[7]["title"])) {						
			if ($pdfName["guide"] == "food-stamp/snap-advocacy-guide") {
				$prefix = '<p><img src="/mhl-shared/images/pdf.gif" /> ';
				$title = 'SNAP Advocacy Guide';
				$href = 'http://www.masslegalservices.org/FoodStampSNAPAdvocacyGuide';
			}
			else if ($pdfName["guide"] == "tafdc-advocacy-guide") {
				$prefix = '<p><img src="/mhl-shared/images/pdf.gif" /> ';
				$title = 'TAFDC Advocacy Guide';
				$href = 'http://www.masslegalservices.org/system/files/library/TAFDC%20Guide%20-%202016.pdf';
			}
			if ($title == 'SNAP Advocacy Guide' || $title == 'TAFDC Advocacy Guide') {
				$list[] = addtolist($listItem, $title, $href, $prefix);						
			}
		} // end of full guide download
		
		// 4c. In addition, for all pages display the ebook download links 	
		$prefix = '<p>Download the entire book as an eBook - ';
		$title = 'Find out how';
		$href = 'http://www.masslegalhelp.org/how-do-i-download-an-ebook-';
		$list[] = addtolist($listItem, $title, $href, $prefix);			
		
		$prefix = '<p><img src="/shared-images/epub_logo_color.png" /> ';
		$title = $pdfDisplayTitle["ePub"];
		$href = $pdfPath["ePub"];
		$list[] = addtolist($listItem, $title, $href, $prefix);			

		$prefix = '<p><img src="/shared-images/kindle.png" /> ';
		$title = $pdfDisplayTitle["mobi"];
		$href = $pdfPath["mobi"];
		$list[] = addtolist($listItem, $title, $href, $prefix);			
		
		// 4d. For the guide level page, display a link for buying a hard copy	
		if ($pdfDisplayTitle["chapter"] == "") {
			if ($pdfName["guide"] == "food-stamp/snap-advocacy-guide") {
				$prefix = '<p>Buy a hard copy from ';
				$title = ' MCLE ($9.95)';
				$href = 'http://www.mcle.org/books-cds/books-catalog.cfm?product_code=2120278B16';
			}
			else if ($pdfName["guide"] == "tafdc-advocacy-guide") {
				$prefix = '<p>Buy a hard copy from ';
				$title = ' MCLE ($9.95)';
				$href = 'http://www.mcle.org/product/catalog/code/2140436B19';
			}
			$list[] = addtolist($listItem, $title, $href, $prefix);		
		}	  // End of ebook download links
	
	//dsm($list);
	return $list;		
}

function addtolist(&$listItem, $title, $href, $prefix) {
	$listItem = array(			
		'data' => array(				
			'#title' => $title,
			'#href' => $href,
			'#type' => 'link',
			),
		'#prefix' => $prefix,
		'#suffix' => '</p>',			
	);
	return $listItem;	
}
